<?php

namespace Tests\Feature;

use App\Models\Admin;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use function route;

class CommentTest extends TestCase
{
    use RefreshDatabase;
    use WithFaker;

    private $admin;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->admin = Admin::factory()->create();
    }

    public function test_comment_index()
    {
        $response = $this->actingAs($this->admin)->get(route('admin.comments.index'));
        $response->assertStatus(302);
        $this->assertAuthenticated();
    }

    public function test_comment_show_not_exist()
    {
        $response = $this->actingAs($this->admin)->get(route('admin.comments.show', 'not_exist'));
        $response->assertStatus(404);
    }

    public function test_comment_show_exist()
    {
        $comment = Comment::factory()->create();
        $response = $this->actingAs($this->admin)->get(route('admin.comments.show', $comment));
        $response->assertStatus(302);
    }

    public function test_comment_change_status_not_exist()
    {

        $response = $this->actingAs($this->admin)->put(route('admin.comments.change_status', 'not_exist'));
        $response->assertStatus(404);
    }

    public function test_comment_change_status_exist_in_index()
    {
        $comment = Comment::factory()->create();
        $response = $this->actingAs($this->admin)->put(route('admin.comments.change_status', $comment));
        $response->assertStatus(302);
        static::assertEquals(!$comment->status, $comment->fresh()->status);
    }



}
